---
  # tasks file for ecomm
- name: Copy Tomcat
  get_url: 
    url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.107/bin/apache-tomcat-9.0.107.tar.gz
    dest: /etc/apache.tar.gz
    mode: '0755'
  when: ansible_pkg_mgr == 'apt'

- name: unzip tomcat
  unarchive:
    src: /etc/apache.tar.gz
    dest: /etc/
    remote_src: true
    mode: '0755'
  when: ansible_pkg_mgr == 'apt'


 

...